Repository devping-kr/NNplanner-BE, pull requests merged in 2024-09, with the labels that each got.

#17 feature: 회원가입 기능 구현
  src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/AuthLoginRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/AuthSignRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthResponseDTO.java
  src/main/java/devping/nnplanner/domain/auth/entity/User.java
  src/main/java/devping/nnplanner/domain/auth/repository/UserRepository.java
  src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
  src/main/java/devping/nnplanner/domain/user/entity/User.java
  src/main/java/devping/nnplanner/global/config/AuditingConfig.java
  src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
  src/main/java/devping/nnplanner/global/entity/BaseTimeEntity.java
  src/main/java/devping/nnplanner/global/exception/ErrorCode.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtAuthenticationFilter.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtAuthorizationFilter.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtUtil.java
  src/main/java/devping/nnplanner/global/jwt/user/UserDetailsImpl.java
  src/main/java/devping/nnplanner/global/jwt/user/UserDetailsServiceImpl.java
Labels: feature

#19 feature: 인증번호 발송/ 인증 기능 구현
  build.gradle
  src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/EmailCodeRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/EmailRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/entity/Email.java
  src/main/java/devping/nnplanner/domain/auth/repository/EmailRepository.java
  src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
  src/main/java/devping/nnplanner/global/config/EmailConfig.java
  src/main/java/devping/nnplanner/global/exception/ErrorCode.java
  src/main/java/devping/nnplanner/global/response/GlobalResponse.java
  src/main/java/devping/nnplanner/global/response/ResponseUtil.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feature

#22 feature: 리프레시 토큰 구현
  build.gradle
  src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthResponseDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthTokenResponseDTO.java
  src/main/java/devping/nnplanner/domain/auth/entity/Email.java
  src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
  src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtAuthenticationFilter.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtUtil.java
  src/main/java/devping/nnplanner/global/jwt/token/RefreshToken.java
  src/main/java/devping/nnplanner/global/jwt/token/RefreshTokenRepository.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feature

#24 add: Docker 이미지 빌드를 위한 Dockerfile 추가
  .github/ISSUE_TEMPLATE/도메인-소문자----기능-한글로-.md
  .github/workflows/google-java-format.yml
  .gitignore
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/devping/nnplanner/NNplannerApplication.java
  src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/AuthLoginRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/AuthSignRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/EmailCodeRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/EmailRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthResponseDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthTokenResponseDTO.java
  src/main/java/devping/nnplanner/domain/auth/entity/Email.java
  src/main/java/devping/nnplanner/domain/auth/entity/User.java
  src/main/java/devping/nnplanner/domain/auth/repository/EmailRepository.java
  src/main/java/devping/nnplanner/domain/auth/repository/UserRepository.java
  src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
  src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
  src/main/java/devping/nnplanner/domain/menu/entity/MonthMenu.java
  src/main/java/devping/nnplanner/domain/menucategory/entity/MenuCategory.java
  src/main/java/devping/nnplanner/domain/openapi/entity/DailyMenu.java
  src/main/java/devping/nnplanner/domain/openapi/entity/Food.java
  src/main/java/devping/nnplanner/domain/servey/entity/AdditionalQuestion.java
  src/main/java/devping/nnplanner/domain/servey/entity/Servey.java
  src/main/java/devping/nnplanner/global/config/AuditingConfig.java
  src/main/java/devping/nnplanner/global/config/EmailConfig.java
  src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
  src/main/java/devping/nnplanner/global/entity/BaseTimeEntity.java
  src/main/java/devping/nnplanner/global/exception/CustomException.java
  src/main/java/devping/nnplanner/global/exception/ErrorCode.java
  src/main/java/devping/nnplanner/global/exception/GlobalExceptionHandler.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtAuthenticationFilter.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtAuthorizationFilter.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtUtil.java
  src/main/java/devping/nnplanner/global/jwt/token/RefreshToken.java
  src/main/java/devping/nnplanner/global/jwt/token/RefreshTokenRepository.java
  src/main/java/devping/nnplanner/global/jwt/user/UserDetailsImpl.java
  src/main/java/devping/nnplanner/global/jwt/user/UserDetailsServiceImpl.java
  src/main/java/devping/nnplanner/global/response/ApiResponse.java
  src/main/java/devping/nnplanner/global/response/GlobalResponse.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/devping/nnplanner/NNplannerApplicationTests.java
Labels: add

#25 fix: OpenJDK 베이스 이미지 변경
  Dockerfile
Labels: fix

#28 feature: 로그아웃 api 구현
  src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
  src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
  src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
  src/main/java/devping/nnplanner/global/exception/ErrorCode.java
  src/main/java/devping/nnplanner/global/jwt/token/BlackList.java
  src/main/java/devping/nnplanner/global/jwt/token/BlackListRepository.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtUtil.java
Labels: feature

#30 fix: health check를 위해 spring security 설정 수정
  src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
Labels: fix

#32 feature: CORS 설정
  src/main/java/devping/nnplanner/global/config/CorsConfig.java
Labels: feature

#33 add: cors 허용 도메인 추가
  src/main/java/devping/nnplanner/global/config/CorsConfig.java
Labels: add

#36 feature: Food openAPI 호출 구현
  build.gradle
  src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemProcessor.java
  src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemReader.java
  src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemWriter.java
  src/main/java/devping/nnplanner/domain/openapi/batch/scheduler/BatchScheduler.java
  src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
  src/main/java/devping/nnplanner/domain/openapi/dto/response/FoodApiResponseDTO.java
  src/main/java/devping/nnplanner/domain/openapi/entity/Food.java
  src/main/java/devping/nnplanner/domain/openapi/repository/FoodRepository.java
  src/main/java/devping/nnplanner/global/config/FoodBatchConfig.java
  src/main/java/devping/nnplanner/global/config/WebClientConfig.java
  src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
  src/main/resources/application-local.yml
Labels: feature

#37 feat: 설문 생성 기능 구현 (#1)
  src/main/java/devping/nnplanner/domain/servey/entity/AdditionalQuestion.java
  src/main/java/devping/nnplanner/domain/servey/entity/Servey.java
  src/main/java/devping/nnplanner/domain/survey/controller/SurveyController.java
  src/main/java/devping/nnplanner/domain/survey/dto/request/SurveyRequestDTO.java
  src/main/java/devping/nnplanner/domain/survey/dto/response/SurveyResponseDTO.java
  src/main/java/devping/nnplanner/domain/survey/entity/Survey.java
  src/main/java/devping/nnplanner/domain/survey/entity/SurveyState.java
  src/main/java/devping/nnplanner/domain/survey/repository/SurveyRepository.java
  src/main/java/devping/nnplanner/domain/survey/service/SurveyService.java
  src/main/java/devping/nnplanner/global/exception/ErrorCode.java
  src/main/resources/application-prod.yml
  src/test/java/devping/nnplanner/domain/survey/service/SurveyServiceTest.java
Labels: feature

#39 feat: 설문 생성 기능 구현 (#1)
  build.gradle
  src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemProcessor.java
  src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemReader.java
  src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemWriter.java
  src/main/java/devping/nnplanner/domain/openapi/batch/scheduler/BatchScheduler.java
  src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
  src/main/java/devping/nnplanner/domain/openapi/dto/response/FoodApiResponseDTO.java
  src/main/java/devping/nnplanner/domain/openapi/entity/Food.java
  src/main/java/devping/nnplanner/domain/openapi/repository/FoodRepository.java
  src/main/java/devping/nnplanner/domain/servey/entity/AdditionalQuestion.java
  src/main/java/devping/nnplanner/domain/servey/entity/Servey.java
  src/main/java/devping/nnplanner/domain/survey/controller/SurveyController.java
  src/main/java/devping/nnplanner/domain/survey/dto/request/SurveyRequestDTO.java
  src/main/java/devping/nnplanner/domain/survey/dto/response/SurveyResponseDTO.java
  src/main/java/devping/nnplanner/domain/survey/entity/Survey.java
  src/main/java/devping/nnplanner/domain/survey/entity/SurveyState.java
  src/main/java/devping/nnplanner/domain/survey/repository/SurveyRepository.java
  src/main/java/devping/nnplanner/domain/survey/service/SurveyService.java
  src/main/java/devping/nnplanner/global/config/FoodBatchConfig.java
  src/main/java/devping/nnplanner/global/config/WebClientConfig.java
  src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
  src/main/java/devping/nnplanner/global/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/devping/nnplanner/domain/survey/service/SurveyServiceTest.java
Labels: feature, fix

#40 feature: 병원 식단 필터 api 구현
  src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemReader.java
  src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemWriter.java
  src/main/java/devping/nnplanner/domain/openapi/batch/hospital/HospitalMenuItemProcessor.java
  src/main/java/devping/nnplanner/domain/openapi/batch/hospital/HospitalMenuItemReader.java
  src/main/java/devping/nnplanner/domain/openapi/batch/hospital/HospitalMenuItemWriter.java
  src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
  src/main/java/devping/nnplanner/domain/openapi/entity/HospitalMenu.java
  src/main/java/devping/nnplanner/domain/openapi/entity/ImportHospitalMenu.java
  src/main/java/devping/nnplanner/domain/openapi/repository/FoodRepository.java
  src/main/java/devping/nnplanner/domain/openapi/repository/HospitalMenuRepository.java
  src/main/java/devping/nnplanner/domain/openapi/repository/ImportHospitalMenuRepository.java
  src/main/java/devping/nnplanner/global/config/FoodBatchConfig.java
  src/main/java/devping/nnplanner/global/config/HospitalBatchConfig.java
  src/main/java/devping/nnplanner/global/response/GlobalResponse.java
  src/main/resources/application-prod.yml
Labels: feature

#42 feature: 학교 정보 호출 api 구현
  src/main/java/devping/nnplanner/domain/openapi/dto/response/SchoolInfoResponseDTO.java
  src/main/java/devping/nnplanner/domain/openapi/entity/SchoolInfo.java
  src/main/java/devping/nnplanner/domain/openapi/repository/SchoolInfoRepository.java
  src/main/java/devping/nnplanner/domain/openapi/service/SchoolInfoService.java
  src/main/java/devping/nnplanner/global/config/WebClientConfig.java
Labels: feature

#43 fix: setter 삭제
  src/main/java/devping/nnplanner/domain/auth/entity/Email.java
  src/main/java/devping/nnplanner/domain/auth/entity/User.java
  src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
  src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
Labels: fix

#48 fix: auth, email 수정
  src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/AuthLoginRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/AuthSignRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/EmailCodeRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/request/EmailRequestDTO.java
  src/main/java/devping/nnplanner/domain/auth/entity/Email.java
  src/main/java/devping/nnplanner/domain/auth/entity/User.java
  src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
  src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtAuthenticationFilter.java
Labels: fix

#53 fix: batch 설정 수정
  src/main/java/devping/nnplanner/NNplannerApplication.java
  src/main/java/devping/nnplanner/global/config/HospitalBatchConfig.java
Labels: fix

#54 배포
  src/main/java/devping/nnplanner/NNplannerApplication.java
  src/main/java/devping/nnplanner/global/config/HospitalBatchConfig.java
Labels: deploy

#63 feature: 식단 자동 생성 api 구현
  src/main/java/devping/nnplanner/NNplannerApplication.java
  src/main/java/devping/nnplanner/domain/menu/entity/MonthMenu.java
  src/main/java/devping/nnplanner/domain/menucategory/entity/MenuCategory.java
  src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/request/MonthMenuAutoRequestDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/response/FoodResponseDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthMenuAutoResponseDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenu.java
  src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenuHospital.java
  src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
  src/main/java/devping/nnplanner/domain/openapi/entity/HospitalMenu.java
  src/main/java/devping/nnplanner/domain/openapi/entity/ImportHospitalMenu.java
  src/main/java/devping/nnplanner/domain/openapi/repository/HospitalMenuRepository.java
  src/main/java/devping/nnplanner/domain/openapi/repository/HospitalMenuRepositoryCustom.java
  src/main/java/devping/nnplanner/domain/openapi/repository/HospitalMenuRepositoryCustomImpl.java
  src/main/java/devping/nnplanner/global/config/QuerydslConfig.java
Labels: feature

#65 feature: 월별 식단 저장 api 구현
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthResponseDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthTokenResponseDTO.java
  src/main/java/devping/nnplanner/domain/menucategory/repository/MenuCategoryRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/request/MonthMenuSaveRequestDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenu.java
  src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenuHospital.java
  src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuHospitalRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
  src/main/java/devping/nnplanner/domain/openapi/repository/HospitalMenuRepositoryCustomImpl.java
Labels: feature

#68 feature: 식단 조회 api 구현
  Dockerfile
  docker-compose.yml
  src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthFoodListResponseDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthMenuPageResponseDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthMenuResponseDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuHospitalRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feature

#70 배포
  Dockerfile
  docker-compose.yml
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthResponseDTO.java
  src/main/java/devping/nnplanner/domain/auth/dto/response/AuthTokenResponseDTO.java
  src/main/java/devping/nnplanner/domain/menucategory/repository/MenuCategoryRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/request/MonthMenuSaveRequestDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthFoodListResponseDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthMenuPageResponseDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthMenuResponseDTO.java
  src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenu.java
  src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenuHospital.java
  src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuHospitalRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
  src/main/java/devping/nnplanner/domain/openapi/repository/HospitalMenuRepositoryCustomImpl.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: deploy

#69 feature: 식단 수정 api 구현
  src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
  src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenu.java
  src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuHospitalRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
Labels: feature

#71 fix: 레디스 컨테이너 이름 설정
  docker-compose.yml
Labels: deploy

#72 deploy: 배포
  docker-compose.yml
  src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
  src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenu.java
  src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuHospitalRepository.java
  src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
Labels: deploy

#73 deploy: 배포
  src/main/resources/application-prod.yml
Labels: deploy

#74 deploy: 배포
  src/main/resources/application-prod.yml
Labels: deploy

#75 fix: 이메일 TTL, 응답 메세지 수정
  src/main/java/devping/nnplanner/domain/auth/entity/Email.java
  src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtAuthorizationFilter.java
Labels: fix

#76 deploy: 배포
  src/main/java/devping/nnplanner/domain/auth/entity/Email.java
  src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
  src/main/java/devping/nnplanner/global/jwt/token/JwtAuthorizationFilter.java
Labels: deploy
