Repository devping-kr/NNplanner-BE, pull requests merged in 2025-04, with the labels that each got.

#234 refactor: 중복 코드 리팩터링, if -> switch 리팩터링
  src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
Labels: refactor

#235 fix: 트랜잭션 추가
  src/main/java/devping/nnplanner/domain/menucategory/service/MenuCategoryService.java
Labels: fix

#236 fix: 트랜잭션 추가
  src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
Labels: fix

#238 deploy : 배포
  src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
  src/main/java/devping/nnplanner/domain/menucategory/service/MenuCategoryService.java
  src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
  src/main/java/devping/nnplanner/domain/survey/dto/response/SurveyDetailResponseDTO.java
  src/main/java/devping/nnplanner/domain/survey/entity/AnswerItemType.java
  src/main/java/devping/nnplanner/domain/survey/entity/Question.java
  src/main/java/devping/nnplanner/domain/survey/entity/SurveyAnswerItem.java
  src/main/java/devping/nnplanner/domain/survey/entity/SurveyResponseDetail.java
  src/main/java/devping/nnplanner/domain/survey/repository/QuestionRepository.java
  src/main/java/devping/nnplanner/domain/survey/repository/ResponseDetailRepository.java
  src/main/java/devping/nnplanner/domain/survey/repository/SurveyAnswerItemRepository.java
  src/main/java/devping/nnplanner/domain/survey/repository/SurveyRepository.java
  src/main/java/devping/nnplanner/domain/survey/repository/SurveyResponseRepository.java
  src/main/java/devping/nnplanner/domain/survey/service/SurveyService.java
  src/main/java/devping/nnplanner/domain/user/controller/UserController.java
  src/main/java/devping/nnplanner/global/exception/ErrorCode.java
Labels: deploy

#239 fix : N+1 발생에 따라 설문상세 조회 로직 수정
  src/main/java/devping/nnplanner/domain/survey/entity/SurveyAnswerItem.java
  src/main/java/devping/nnplanner/domain/survey/entity/SurveyResponseDetail.java
  src/main/java/devping/nnplanner/domain/survey/repository/ResponseDetailRepository.java
  src/main/java/devping/nnplanner/domain/survey/repository/SurveyResponseRepository.java
  src/main/java/devping/nnplanner/domain/survey/service/SurveyService.java
  src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: fix

#241 deploy : 배포
  src/main/java/devping/nnplanner/domain/survey/entity/SurveyAnswerItem.java
  src/main/java/devping/nnplanner/domain/survey/entity/SurveyResponseDetail.java
  src/main/java/devping/nnplanner/domain/survey/repository/ResponseDetailRepository.java
  src/main/java/devping/nnplanner/domain/survey/repository/SurveyResponseRepository.java
  src/main/java/devping/nnplanner/domain/survey/service/SurveyService.java
  src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: deploy
